### ISSUE TITLE
0.0.2 seems to break previous installation

### ISSUE THREAD

**Issue by matteocrippa** [IBM-Swift/CCurl#1]
Seems that 0.0.2 breaks installation with this error:

```
Target: x86_64-unknown-linux-gnu
/root/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-ubuntu15.10/usr/bin/swift -frontend -interpret /data/swift/tori/Packages/CCurl/Package.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -I /root/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-ubuntu15.10/usr/lib/swift/pm -module-name Package -lPackageDescription -- -fileno 3
/data/swift/tori/Packages/CCurl/Package.swift:19:22: error: incorrect argument labels in call (have 'name:pkgConfig:providers:', expected 'name:targets:dependencies:')
let package = Package(
                     ^
```

looking at the error seems pretty related to the new struct of the package file

**Comment by rfdickerson** [comment]
Hi @matteocrippa we have decided to bring CCurl up to 04-25 snapshot that has the new support for providers description (apt and brew).

**Comment by matteocrippa** [comment]
@rfdickerson yep I noticed so, thx. Is there a chance to upgrade Kitura-Net to a new version (0.11?) in order to make use of this? Because my old release of [tori](https://github.com/boostcode/tori/blob/feature/usermanagement/Package.swift) was stuck in compiling due to this error, and managing to upgrade to 04-25 make other dependencies not to be supported yet.

**Comment by michalkalinowski-** [comment]
+1 I'm trying to build Kitura 0.11 and the build fails because of CCurl:
Kitura depends on Kitura-net that depends on CCurl. Current recommended swift version in Kitura readme is DEVELOPMENT-SNAPSHOT-2016-03-24-a

I've also tried building with the latest dev snapshot, but then multiple packages fail to build (ex. swiftyJSON)

Maybe you could tag CCurl with new package format as 0.1 and then when building Kitura-net the previous version would be fetched (currently Kitura-net depends on 0.0)

**Comment by matteocrippa** [comment]
@michalkalinowski- do you managed to use Kitura 0.10 or another version?

**Comment by matteocrippa** [comment]
I self-reply, moving to Kitura 0.11 fixes the issue
